In [2]:
import pandas as pd
import numpy as np

### Function to read the .txt files into a DataFrame

In [3]:

df_list = []
file_locs = ['../scraped_data/data.txt','../scraped_data/cardekho.txt']
for file in file_locs:
    with open(file, 'r', encoding='utf-8') as rf:
        for line in rf:
            inp = eval(line)
            main_dict = {}

            for key, value in inp.items():
                if(key == 'info'):
                    for keyinfo,valueinfo in inp[key].items():
                        main_dict[keyinfo] = valueinfo   
                else:
                        main_dict[key] = value
            df_list.append(main_dict)

df = pd.DataFrame(df_list)

The data for this project has been scraped from both Cars24 and CarDekho. Both have been stored in two seperate .txt files, 'data.txt' and 'cardekho.txt', in different ways. Each line of the .txt file is a python dictionary that stores relevant information about the car. The above function reads in each line, converts it to a dictionary, and appends it to a list of dictionaries. This list is then converted into a dataframe df.

# Basic Overview of the Data

In [4]:
df.head()

,model,price,price_score,plate,Reg. year,Fuel,KM driven,Transmission,Engine capacity,Ownership,Make year,Spare key,Reg number,Insurance,Insurance type
0,2020 Jeep Compass LONGITUDE PLUS 1.4 PETROL AT,₹8.50 lakh,STEAL DEAL according to our Price Indicator.,DL-10,Jul 2020,Petrol,"116,562 km",Automatic,1368cc,1st,Feb 2020,No,******8927,Nov 2026,3rd Party
1,2016 Mahindra XUV500 W6 AT 1.99,₹4.51 lakh,FAIR PRICE according to our Price Indicator.,DL-10,Aug 2016,Diesel,"238,933 km",Automatic,1997cc,1st,Jun 2016,No,******6357,NaN,NaN
2,2012 Hyundai Eon D-LITE,₹0.84 lakh,STEAL DEAL according to our Price Indicator.,UP-15,Jan 2013,CNG,"94,507 km",Manual,814cc,2nd,Jan 2012,No,******2716,Nov 2026,3rd Party
3,2013 Hyundai i20 SPORTZ 1.2,₹1.81 lakh,STEAL DEAL according to our Price Indicator.,DL-10,Mar 2013,CNG,"120,121 km",Manual,1197cc,2nd,Feb 2013,No,******7982,Dec 2026,3rd Party
4,2014 Honda City 1.5L I-VTEC SV,₹3.07 lakh,STEAL DEAL according to our Price Indicator.,DL-4C,May 2014,Petrol,"77,884 km",Manual,1497cc,2nd,Apr 2014,No,******9657,NaN,NaN

In [23]:
print(f"There are {df.shape[0]} rows and {df.shape[1]} columns in the dataset.")

There are 15410 rows and 15 columns in the dataset.

In [5]:
print(f"There are {df.duplicated().value_counts().iloc[1]} duplicated rows.")

There are 2496 duplicated rows.

Since the data has been scraped over multiple days, the same listings get captured by the scraper. Additionally, CarDekho also lists some cars found on Cars24, which could be contributing to the number of duplicates.

# Modifying Datatypes :

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15410 entries, 0 to 15409
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   model            15410 non-null  object
 1   price            15410 non-null  object
 2   price_score      15110 non-null  object
 3   plate            15410 non-null  object
 4   Reg. year        15410 non-null  object
 5   Fuel             15410 non-null  object
 6   KM driven        15410 non-null  object
 7   Transmission     15410 non-null  object
 8   Engine capacity  15107 non-null  object
 9   Ownership        15410 non-null  object
 10  Make year        15410 non-null  object
 11  Spare key        9484 non-null   object
 12  Reg number       9484 non-null   object
 13  Insurance        4296 non-null   object
 14  Insurance type   10222 non-null  object
dtypes: object(15)
memory usage: 1.8+ MB

Almost all rows are of an incorrect datatype. THis is to be rectified. Many rows are also null, some having so few values that using them for any meaningful analysis is almost impossible. They are to be dropped. 

Certain information given by Cars24 about cars is not present in CarDekho. For example, `Spare key` and `Reg number` are not provided on CarDekho, which explains their equal number of missing values. 

Insurance and Insurance type have inconsistent number of nulls, even though they are related to each other. One reason for this is the CarDekho-v/s-Cars24 missing data mentioned in the previous line.

In [7]:
# creating a copy:
data = df.copy()

In [8]:
# Modifying Ownership :
maps = {'1st':1, '2nd':2, '3rd':3, '4th':4, '5th': 5, '6th':6, '7th':7, 
        'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fourth Owner':4, 'Fifth Owner':5}
data['Ownership'] = data['Ownership'].replace(maps)

C:\Users\sisfi\AppData\Local\Temp\ipykernel_14440\2707634852.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Ownership'] = data['Ownership'].replace(maps)

`Ownership` column was stored as a string, making it difficult to visualise.

In [9]:
# trimming model column :
data['model'] = data['model'].str.upper()
data['model'] = data['model'].str.replace('\n',' ') # cleaning up the newlines
data['model'] = data['model'].str.split(' ').map(lambda x: x[1]+' '+x[2] if x[2] != 'SUZUKI' else x[1]+' '+x[2]+' '+x[3])
data.loc[data['model'] == 'MARUTI SUZUKI SWIFT','model'] = 'MARUTI SWIFT' # maruti suzuki swift and maruti suzuki are the same car.
data['model'].value_counts()[:10]

model
HONDA CITY       781
HYUNDAI CRETA    766
MARUTI SWIFT     706
KIA SELTOS       517
HYUNDAI GRAND    515
HONDA AMAZE      486
MARUTI WAGON     424
TATA NEXON       418
HYUNDAI I10      398
MG HECTOR        342
Name: count, dtype: int64

The original `model` column of the car included a lot of redundant information such as the year, fuel-type, etc. that already have dedicated columns for it. Hence, these components are dropped. Readability has also improved.

One problem that arose here is that Maruti Swift and Maruti Suzuki Swift were being errenuosly considered to be separate vehicles despite the fact that they are the same. This edge case is also handled.

In [10]:
# replacing price column :
def price_conversion(x):
    x = x.lower().replace('₹','')

    if(x.endswith('lakh')):
        x = x.replace('lakh','')
        x = float(x)*100000

    elif(x.endswith('crore')):
        x = x.replace('crore', '')
        x = float(x)*10000000
    elif(x.endswith('thousand')):
        x = x.replace('thousand','')
        x = float(x)*1000
    
    return(x)

data['price'] = data['price'].map(price_conversion)

In [11]:
# converting KM driven and engine capacity column:
data['KM driven'] = data['KM driven'].str.replace(r'[A-Za-z,\s]+', '', regex=True).astype('int')
data['Engine capacity'] = data['Engine capacity'].str.strip().str.replace('cc','').astype('Float64')

In [12]:
# trimming price_score column :
data['price_score'] = data['price_score'].replace('NA', np.nan)
data.loc[data['price_score'].notna(), 'price_score'] = data.loc[data['price_score'].notna(), 'price_score'].str.split(' ').map(lambda x: x[0]+' '+x[1])

This change only keeps the basic price evaluation label of the Cars24 listing, improving readability.

In [13]:
# converting Reg. year and Make year
data['Reg. year'] = pd.to_datetime(data['Reg. year']).dt.year
data['Make year'] = pd.to_datetime(data['Make year']).dt.year

C:\Users\sisfi\AppData\Local\Temp\ipykernel_14440\4109392050.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['Reg. year'] = pd.to_datetime(data['Reg. year']).dt.year
C:\Users\sisfi\AppData\Local\Temp\ipykernel_14440\4109392050.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['Make year'] = pd.to_datetime(data['Make year']).dt.year

The Year columns, previously stored as objects have been converted to datetime objects.

# Examining Nulls :

In [14]:
df.isna().sum()

model                  0
price                  0
price_score          300
plate                  0
Reg. year              0
Fuel                   0
KM driven              0
Transmission           0
Engine capacity      303
Ownership              0
Make year              0
Spare key           5926
Reg number          5926
Insurance          11114
Insurance type      5188
dtype: int64

- `Spare Key` and `Reg Number` both have same number of null values, because they have been sourced from CarDekho, which does not provide this info.
- `price_score` field will have more nulls than depicted, because this info is not given in the CarDekho records either.
- `Engine capacity` nulls can be interpolated from other cars of the same model.
- `Insurance type` has less number of nulls than `Insurance`, because CarDekho data doesn't provide data for the 'Insurance' column.

In [15]:
# Replacing Insurance type nulls w/ unknown:
data.loc[data['Insurance type'].isna(),'Insurance type'] = 'Unknown'

`Insurance type` is a meaningful attribute of a vehicle. If a seller does not provide Insurance information while selling their car, it might be a red flag. A relatively new car of a top-tier model not having insurance information is curious, and it might be a genuine signal that can be picked up by an ML model. Hence, instead of dropping the whole column altogether, the nulls have been replaced with `Unknown`.

In [16]:
# Replacing Engine capacity with other cars of the same make :
data['Engine capacity'] = data['Engine capacity'].fillna(
    data.groupby(['model', 'Make year'])['Engine capacity'].transform('mean'))

In [24]:
# for cars where model + year are too limiting :

data['Engine capacity'] = data['Engine capacity'].fillna(
    data.groupby('model')['Engine capacity'].transform('median')
)

In [18]:
data[data['Engine capacity'].isna()] = 0

Cars belonging to the same year-model combination are almost certain to have the same engine capacities. Hence, they have been interpolated. 

Still, the above imputation method still left some nulls. These vehicles where simply imputed with the median engine capacity for their specific model. This is likely to be less accurate. 

Cars that still had null values were EVs, which do not have engine capacities in the first place. They were replaced with 0.

# Dropping Unnecessary Rows and Columns :

In [25]:
data.drop_duplicates(inplace=True, keep='first')
print(f"After dropping duplicates, {data.shape[0]} rows remain.")

After dropping duplicates, 12757 rows remain.

In [20]:
del data['Reg number']
del data['Spare key']
del data['Insurance']

In [21]:
data.head()

,model,price,price_score,plate,Reg. year,Fuel,KM driven,Transmission,Engine capacity,Ownership,Make year,Insurance type
0,JEEP COMPASS,850000.0,STEAL DEAL,DL-10,2020,Petrol,116562,Automatic,1368.0,1,2020,3rd Party
1,MAHINDRA XUV500,451000.0,FAIR PRICE,DL-10,2016,Diesel,238933,Automatic,1997.0,1,2016,Unknown
2,HYUNDAI EON,84000.0,STEAL DEAL,UP-15,2013,CNG,94507,Manual,814.0,2,2012,3rd Party
3,HYUNDAI I20,181000.0,STEAL DEAL,DL-10,2013,CNG,120121,Manual,1197.0,2,2013,3rd Party
4,HONDA CITY,307000.0,STEAL DEAL,DL-4C,2014,Petrol,77884,Manual,1497.0,2,2014,Unknown