In [4]:
import pandas as pd
import numpy as np
from data_clean_export import data

There are 2351 duplicated rows.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14928 entries, 0 to 14927
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   model            14928 non-null  object
 1   price            14928 non-null  object
 2   price_score      14628 non-null  object
 3   plate            14928 non-null  object
 4   Reg. year        14928 non-null  object
 5   Fuel             14928 non-null  object
 6   KM driven        14928 non-null  object
 7   Transmission     14928 non-null  object
 8   Engine capacity  14634 non-null  object
 9   Ownership        14928 non-null  object
 10  Make year        14928 non-null  object
 11  Spare key        9165 non-null   object
 12  Reg number       9165 non-null   object
 13  Insurance        4113 non-null   object
 14  Insurance type   9876 non-null   object
dtypes: object(15)
memory usage: 1.7+ MB

c:\Users\sisfi\OneDrive\Desktop\DataA\smart-buy-classifier\notebooks\data_clean_export.py:96: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['Reg. year'] = pd.to_datetime(data['Reg. year']).dt.year
c:\Users\sisfi\OneDrive\Desktop\DataA\smart-buy-classifier\notebooks\data_clean_export.py:97: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['Make year'] = pd.to_datetime(data['Make year']).dt.year

In [5]:
data.head()

,model,price,price_score,plate,Reg. year,Fuel,KM driven,Transmission,Engine capacity,Ownership,Make year,Insurance type
0,JEEP COMPASS,850000.0,STEAL DEAL,DL,2020,Petrol,116562,Automatic,1368.0,1st,2020,3rd Party
1,MAHINDRA XUV500,451000.0,FAIR PRICE,DL,2016,Diesel,238933,Automatic,1997.0,1st,2016,Unknown
2,HYUNDAI EON,84000.0,STEAL DEAL,UP,2013,CNG,94507,Manual,814.0,2nd,2012,3rd Party
3,HYUNDAI I20,181000.0,STEAL DEAL,DL,2013,CNG,120121,Manual,1197.0,2nd,2013,3rd Party
4,HONDA CITY,307000.0,STEAL DEAL,DLC,2014,Petrol,77884,Manual,1497.0,2nd,2014,Unknown

In [13]:
# Creating the car age feature :
data['car_age'] = 2026 - data['Reg. year']

In [ ]:
# creating NGT_life column
data['ngt_life'] = 10 - data['car_age']
data['ngt_critical'] = data['ngt_life'].map(lambda x: 'Yes' if x<=2 else 'No') # binary column
data['ngt_critical'].value_counts()

ngt_critical
Yes    6359
No     6070
Name: count, dtype: int64

In [ ]:
#RTO feature

In [19]:
# km_per_year column:
data['km_per_year'] = (data['KM driven']/data['car_age']).round(2)
data['km_per_year']

0        19427.00
1        23893.30
2         7269.77
3         9240.08
4         6490.33
           ...
14919    10250.00
14922    21000.00
14924     3731.22
14925    10555.56
14926     8313.50
Name: km_per_year, Length: 12429, dtype: float64

In [25]:
# Modifying Ownership :
maps = {'1st':1, '2nd':2, '3rd':3, '4th':4, '5th': 5, '6th':6, '7th':7, 
        'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fourth Owner':4, 'Fifth Owner':5}
data['Ownership'] = data['Ownership'].replace(maps)

C:\Users\sisfi\AppData\Local\Temp\ipykernel_17536\2707634852.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Ownership'] = data['Ownership'].replace(maps)

In [26]:
data.head()

,model,price,price_score,plate,Reg. year,Fuel,KM driven,Transmission,Engine capacity,Ownership,Make year,Insurance type,car_age,ngt_life,ngt_critical,km_per_year
0,JEEP COMPASS,850000.0,STEAL DEAL,DL,2020,Petrol,116562,Automatic,1368.0,1,2020,3rd Party,6,4,No,19427.00
1,MAHINDRA XUV500,451000.0,FAIR PRICE,DL,2016,Diesel,238933,Automatic,1997.0,1,2016,Unknown,10,0,Yes,23893.30
2,HYUNDAI EON,84000.0,STEAL DEAL,UP,2013,CNG,94507,Manual,814.0,2,2012,3rd Party,13,-3,Yes,7269.77
3,HYUNDAI I20,181000.0,STEAL DEAL,DL,2013,CNG,120121,Manual,1197.0,2,2013,3rd Party,13,-3,Yes,9240.08
4,HONDA CITY,307000.0,STEAL DEAL,DLC,2014,Petrol,77884,Manual,1497.0,2,2014,Unknown,12,-2,Yes,6490.33